name: JMeter Test

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Mkdir test result directory
        run: mkdir testresults
      - name: Run test plan
        uses: docker://justb4/jmeter:latest
        with:
          args: -n -t ./test_plan.jmx -l ./testresults.log -e -o ./testresults
      - name: Upload test result
        uses: actions/upload-artifact@v1
        name: test_results
        path: testresults*